run_name: duet_Llama-3.1-8B-Instruct_city_forget_popular_5_npo_lora_r32_lalpha64_ldrop0p0_lr1e-5_beta0p5_alpha1p0_gamma1p0
source_run_dir: "/Users/valerii.kropotin/\u041D\u041E\u0414/Diploma/open-unlearning/metrics-ep5-all/saves-clean/unlearn/duet_Llama-3.1-8B-Instruct_city_forget_popular_5_npo_lora_r32_lalpha64_ldrop0p0_lr1e-5_beta0p5_alpha1p0_gamma1p0"
split_bucket: duet_popular
lr: 1e-5
method: npo
experiment: unlearn/duet/grad_ascent_lora.yaml
trainer_name: NPO
model_name: Llama-3.1-8B-Instruct-lora
trainer_handler: NPO
dataset:
  forget_split: city_forget_popular_5
  retain_split: city_fast_retain_500
  holdout_split: city_fast_retain_500
  question_key: question
model_summary:
  use_lora: true
  pretrained_model_name_or_path: /data/home/vkropoti/unlearning/SwetieePawsss/DUET_ft_models
  model_subfolder: llama-3.1-8b-instruct-tripunlamb-ft
  tokenizer_pretrained_model_name_or_path: /data/home/vkropoti/unlearning/SwetieePawsss/DUET_ft_models
  tokenizer_subfolder: llama-3.1-8b-instruct-tripunlamb-ft
  lora_config:
    target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    lora_alpha: 64
    lora_dropout: 0.0
    r: 32
    bias: none
    task_type: CAUSAL_LM
trainer_args:
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 2
  learning_rate: 1.0e-05
  bf16: true
  bf16_full_eval: true
  logging_steps: 4
  output_dir: ${paths.output_dir}
  logging_dir: ${trainer.args.output_dir}/logs
  report_to: tensorboard
  ddp_find_unused_parameters: false
  gradient_checkpointing: false
  optim: paged_adamw_32bit
  save_strategy: steps
  save_only_model: true
  weight_decay: 0.0
  do_train: true
  do_eval: false
  eval_on_start: false
  eval_strategy: 'no'
  num_train_epochs: 5
  seed: 0
  lr_scheduler_type: constant
  warmup_ratio: 0.1
  remove_unused_columns: false
  save_steps: 8
  save_total_limit: 12
  logging_strategy: steps
  save_safetensors: true
  load_best_model_at_end: false
method_args:
  gamma: 1.0
  alpha: 1.0
  retain_loss_type: NLL
  beta: 0.5
overrides:
- experiment=unlearn/duet/grad_ascent_lora.yaml
- trainer=NPO
- task_name=duet_Llama-3.1-8B-Instruct_city_forget_popular_5_npo_lora_r32_lalpha64_ldrop0p0_lr1e-5_beta0p5_alpha1p0_gamma1p0
- model=Llama-3.1-8B-Instruct-lora
- forget_split=city_forget_popular_5
- retain_split=city_fast_retain_500
- model.model_args.pretrained_model_name_or_path=/data/home/vkropoti/unlearning/SwetieePawsss/DUET_ft_models
- model.tokenizer_args.pretrained_model_name_or_path=/data/home/vkropoti/unlearning/SwetieePawsss/DUET_ft_models
- model.model_args.device_map=auto
- ++model.model_args.low_cpu_mem_usage=true
- model.lora_config.r=32
- model.lora_config.lora_alpha=64
- model.lora_config.lora_dropout=0.0
- trainer.args.per_device_train_batch_size=16
- trainer.args.gradient_accumulation_steps=2
- trainer.args.num_train_epochs=5
- trainer.args.learning_rate=1e-5
- trainer.method_args.beta=0.5
- trainer.method_args.alpha=1.0
- trainer.method_args.gamma=1.0
- trainer.method_args.retain_loss_type=NLL
- +trainer.trace_jsonl=true
- retain_logs_path=null
- ++trainer.args.save_strategy=steps
- ++trainer.args.save_steps=8
- ++trainer.args.save_total_limit=12
- ++trainer.args.logging_strategy=steps
- ++trainer.args.logging_steps=4
- ++trainer.args.save_safetensors=true
- ++trainer.args.load_best_model_at_end=false
- +model.model_args.subfolder=llama-3.1-8b-instruct-tripunlamb-ft
- +model.tokenizer_args.subfolder=llama-3.1-8b-instruct-tripunlamb-ft
- paths.output_dir=/data/home/vkropoti/unlearning/saves/unlearn/duet_Llama-3.1-8B-Instruct_city_forget_popular_5_npo_lora_r32_lalpha64_ldrop0p0_lr1e-5_beta0p5_alpha1p0_gamma1p0
hydra_config:
  model:
    use_lora: true
    model_args:
      pretrained_model_name_or_path: /data/home/vkropoti/unlearning/SwetieePawsss/DUET_ft_models
      attn_implementation: eager
      torch_dtype: bfloat16
      base_model_name_or_path: null
      low_cpu_mem_usage: true
      device_map: auto
      subfolder: llama-3.1-8b-instruct-tripunlamb-ft
    tokenizer_args:
      pretrained_model_name_or_path: /data/home/vkropoti/unlearning/SwetieePawsss/DUET_ft_models
      subfolder: llama-3.1-8b-instruct-tripunlamb-ft
    lora_config:
      target_modules:
      - q_proj
      - k_proj
      - v_proj
      - o_proj
      lora_alpha: 64
      lora_dropout: 0.0
      r: 32
      bias: none
      task_type: CAUSAL_LM
    template_args:
      apply_chat_template: true
      system_prompt: You are terse and fact-only QA assistant. Reply to the question
        clearly with few-words correct answer.
      system_prompt_with_special_tokens: '<|begin_of_text|><|start_header_id|>system<|end_header_id|>


        You are terse and fact-only QA assistant. Reply to the question clearly with
        few-words correct answer.<|eot_id|>'
      user_start_tag: '<|start_header_id|>user<|end_header_id|>


        '
      user_end_tag: <|eot_id|>
      asst_start_tag: '<|start_header_id|>assistant<|end_header_id|>


        '
      asst_end_tag: <|eot_id|>
      date_string: 10 Apr 2025
  trainer:
    handler: NPO
    args:
      per_device_train_batch_size: 16
      per_device_eval_batch_size: 16
      gradient_accumulation_steps: 2
      learning_rate: 1.0e-05
      bf16: true
      bf16_full_eval: true
      logging_steps: 4
      output_dir: ${paths.output_dir}
      logging_dir: ${trainer.args.output_dir}/logs
      report_to: tensorboard
      ddp_find_unused_parameters: false
      gradient_checkpointing: false
      optim: paged_adamw_32bit
      save_strategy: steps
      save_only_model: true
      weight_decay: 0.0
      do_train: true
      do_eval: false
      eval_on_start: false
      eval_strategy: 'no'
      num_train_epochs: 5
      seed: 0
      lr_scheduler_type: constant
      warmup_ratio: 0.1
      remove_unused_columns: false
      save_steps: 8
      save_total_limit: 12
      logging_strategy: steps
      save_safetensors: true
      load_best_model_at_end: false
    method_args:
      gamma: 1.0
      alpha: 1.0
      retain_loss_type: NLL
      beta: 0.5
    trace_jsonl: true
  data:
    forget:
      DUET_QA_forget:
        handler: QADataset
        args:
          hf_args:
            path: SwetieePawsss/DUET
            split: ${forget_split}
          question_key: ${question_key}
          answer_key: answer
          max_length: 512
    retain:
      DUET_QA_retain:
        handler: QADataset
        args:
          hf_args:
            path: SwetieePawsss/DUET
            split: ${retain_split}
          question_key: ${question_key}
          answer_key: answer
          max_length: 512
    anchor: forget
  collator:
    DataCollatorForSupervisedDataset:
      handler: DataCollatorForSupervisedDataset
      args:
        padding_side: right
  eval:
    duet:
      metrics:
        forget_qa_rouge:
          datasets:
            DUET_QA_forget:
              handler: QADataset
              args:
                hf_args:
                  path: SwetieePawsss/DUET
                  split: ${eval.duet.forget_split}
                question_key: ${eval.duet.question_key}
                answer_key: answer
                max_length: 512
                predict_with_generate: true
          collators:
            DataCollatorForSupervisedDataset:
              handler: DataCollatorForSupervisedDataset
              args:
                padding_side: left
                index: index
          generation_args:
            do_sample: false
            top_p: null
            temperature: null
            max_new_tokens: 64
            use_cache: true
            repetition_penalty: null
            no_repeat_ngram_size: null
          handler: rouge
          rouge_type: rougeL_recall
          batch_size: ${eval.duet.batch_size}
        holdout_qa_rouge:
          datasets:
            DUET_QA_holdout:
              handler: QADataset
              args:
                hf_args:
                  path: SwetieePawsss/DUET
                  split: ${eval.duet.holdout_split}
                question_key: ${eval.duet.question_key}
                answer_key: answer
                max_length: 512
                predict_with_generate: true
          collators:
            DataCollatorForSupervisedDataset:
              handler: DataCollatorForSupervisedDataset
              args:
                padding_side: left
                index: index
          generation_args:
            do_sample: false
            top_p: null
            temperature: null
            max_new_tokens: 64
            use_cache: true
            repetition_penalty: null
            no_repeat_ngram_size: null
          handler: rouge
          rouge_type: rougeL_recall
          batch_size: ${eval.duet.batch_size}
      handler: DUETEvaluator
      output_dir: ${paths.output_dir}
      overwrite: false
      forget_split: ${forget_split}
      holdout_split: ${holdout_split}
      retain_logs_path: ${retain_logs_path}
      question_key: ${question_key}
      batch_size: 8
  paths:
    root_dir: .
    data_dir: ${paths.root_dir}/data/
    datasets: ${paths.root_dir}/configs/data/datasets
    output_dir: /data/home/vkropoti/unlearning/saves/unlearn/duet_Llama-3.1-8B-Instruct_city_forget_popular_5_npo_lora_r32_lalpha64_ldrop0p0_lr1e-5_beta0p5_alpha1p0_gamma1p0
    work_dir: ${hydra:runtime.cwd}
  forget_split: city_forget_popular_5
  retain_split: city_fast_retain_500
  holdout_split: ${retain_split}
  retain_logs_path: null
  question_key: question
  task_name: duet_Llama-3.1-8B-Instruct_city_forget_popular_5_npo_lora_r32_lalpha64_ldrop0p0_lr1e-5_beta0p5_alpha1p0_gamma1p0
  mode: unlearn
source_files:
  config_yaml: "/Users/valerii.kropotin/\u041D\u041E\u0414/Diploma/open-unlearning/metrics-ep5-all/saves-clean/unlearn/duet_Llama-3.1-8B-Instruct_city_forget_popular_5_npo_lora_r32_lalpha64_ldrop0p0_lr1e-5_beta0p5_alpha1p0_gamma1p0/.hydra/config.yaml"
  overrides_yaml: "/Users/valerii.kropotin/\u041D\u041E\u0414/Diploma/open-unlearning/metrics-ep5-all/saves-clean/unlearn/duet_Llama-3.1-8B-Instruct_city_forget_popular_5_npo_lora_r32_lalpha64_ldrop0p0_lr1e-5_beta0p5_alpha1p0_gamma1p0/.hydra/overrides.yaml"
  merged_summary_tsv: "/Users/valerii.kropotin/\u041D\u041E\u0414/Diploma/open-unlearning/metrics-ep5-all/saves-clean/unlearn/duet_Llama-3.1-8B-Instruct_city_forget_popular_5_npo_lora_r32_lalpha64_ldrop0p0_lr1e-5_beta0p5_alpha1p0_gamma1p0/checkpoint_evals_merged/summary.tsv"
  trajectory_metrics_json: "/Users/valerii.kropotin/\u041D\u041E\u0414/Diploma/open-unlearning/metrics-ep5-all/saves-clean/unlearn/duet_Llama-3.1-8B-Instruct_city_forget_popular_5_npo_lora_r32_lalpha64_ldrop0p0_lr1e-5_beta0p5_alpha1p0_gamma1p0/checkpoint_evals_merged/trajectory_metrics.json"
